image: ruby:2.4.0
pipelines:
  branches:
    master:
      - step:
          deployment: production
          script:
            - gem uninstall bundler
            - gem install bundler -v 2.0.2
            - bundle install
            - bundle exec middleman build
