image: ruby:2.6.5
pipelines:
  branches:
    master:
      - step:
          deployment: production
          script:
            - apt-get update
            - apt-get install curl software-properties-common
            - curl -sL https://deb.nodesource.com/setup_13.x | sudo bash -
            - apt-get install nodejs
            - node -v
            - gem install bundler -v 2.0.2
            - bundle install
            - bundle exec middleman build
